CREATE TABLE `books` (
	`id` INT UNSIGNED PRIMARY KEY AUTO_INCREMENT,
	`name` VARCHAR(255) NOT NULL,
	`description` VARCHAR(255) NOT NULL DEFAULT ''
);

CREATE TABLE `chapters` (
	`id` INT UNSIGNED PRIMARY KEY AUTO_INCREMENT,
	`book_id` INT UNSIGNED NOT NULL,
	`chapter` INT UNSIGNED NOT NULL
);

CREATE TABLE `verses` (
	`id` INT UNSIGNED PRIMARY KEY AUTO_INCREMENT,
	`chapter_id` INT UNSIGNED NOT NULL,
	`text` TEXT NOT NULL,

	FULLTEXT (`text`)
);
